window.BABY_TRACKER_PAYLOAD = {
  appName: "Little Rhythm",
  timezone: "America/New_York",
  child: {
    name: "Milo",
    ageLabel: "8 months old",
  },
  caregivers: [
    { name: "Julian", role: "Dad", active: true },
    { name: "Avery", role: "Mom", active: true },
    { name: "Nina", role: "Grandma", active: false },
  ],
  quickActions: [
    { id: "sleep", title: "Nap", detail: "Start or end sleep", icon: "☾" },
    { id: "feed", title: "Feed", detail: "Bottle or solids", icon: "◔" },
    { id: "diaper", title: "Diaper", detail: "Wet or dirty", icon: "◌" },
    { id: "note", title: "Note", detail: "Mood or milestone", icon: "✦" },
  ],
  timeline: [
    {
      id: "evt-1",
      type: "feed",
      title: "Bottle",
      detail: "6 oz formula",
      time: "2026-04-28T06:45:00-04:00",
      caregiver: "Julian",
    },
    {
      id: "evt-2",
      type: "diaper",
      title: "Diaper change",
      detail: "Wet",
      time: "2026-04-28T07:10:00-04:00",
      caregiver: "Julian",
    },
    {
      id: "evt-3",
      type: "sleep",
      title: "Morning nap",
      detail: "1h 18m",
      durationMinutes: 78,
      time: "2026-04-28T08:52:00-04:00",
      endedAt: "2026-04-28T10:10:00-04:00",
      caregiver: "Avery",
    },
    {
      id: "evt-4",
      type: "feed",
      title: "Breakfast solids",
      detail: "Banana + yogurt",
      time: "2026-04-28T10:35:00-04:00",
      caregiver: "Avery",
    },
    {
      id: "evt-5",
      type: "note",
      title: "Mood note",
      detail: "Very smiley after breakfast, a little clingy before nap.",
      time: "2026-04-28T11:05:00-04:00",
      caregiver: "Avery",
    },
    {
      id: "evt-6",
      type: "diaper",
      title: "Diaper change",
      detail: "Wet + dirty",
      time: "2026-04-28T11:42:00-04:00",
      caregiver: "Julian",
    },
    {
      id: "evt-7",
      type: "sleep",
      title: "Afternoon nap started",
      detail: "Settled quickly",
      time: "2026-04-28T13:48:00-04:00",
      caregiver: "Julian",
      active: true,
    },
  ],
  upcoming: [
    "Offer solids around 3:45 PM",
    "Try stroller walk before dinner",
    "Bath usually starts at 6:50 PM",
  ],
  insightSeeds: [
    "Morning naps are most reliable when the first bottle lands before 7:00 AM.",
    "Wet diapers are averaging every 2.4 hours today, which feels comfortably on rhythm.",
    "The last three solid feeds went better earlier in the wake window than right before sleep.",
  ],
  noteSeeds: [
    "Possible top tooth coming in.",
    "Loved banana yogurt more than oatmeal this morning.",
    "Fell asleep faster with blackout curtains and white noise.",
  ],
};
